/**
 * Task Actions
 * Create and update tasks via workflow automation
 */

import { createAdminSupabaseClient } from '@/lib/supabaseAdmin';
import { interpolateTemplate, getNestedValue } from '../templating';
import type { CreateTaskConfig, UpdateTaskConfig, WorkflowContext } from '@/types/workflows';
import { addDays } from 'date-fns';
import logger from '@/lib/utils/logger';

/**
 * Execute create task action
 * 
 * @param config - Task creation configuration
 * @param context - Workflow context
 * @returns Action result with created task details
 */
export async function executeCreateTask(
  config: CreateTaskConfig | unknown,
  context: WorkflowContext
): Promise<{ output: unknown }> {
  const taskConfig = config as CreateTaskConfig;
  const supabase = createAdminSupabaseClient();
  
  // Get project ID from config or context
  let projectId: string | undefined;
  
  if (taskConfig.project_id) {
    projectId = interpolateTemplate(taskConfig.project_id, context);
  } else if (taskConfig.project_field) {
    const fieldValue = getNestedValue(context, taskConfig.project_field);
    projectId = typeof fieldValue === 'string' ? fieldValue : undefined;
  }
  
  if (!projectId) {
    throw new Error('No project ID found for task creation');
  }
  
  // Get assignee ID if specified
  let assigneeId: string | null = null;
  if (taskConfig.assignee_field) {
    const fieldValue = getNestedValue(context, taskConfig.assignee_field);
    assigneeId = typeof fieldValue === 'string' ? fieldValue : null;
  }
  
  // Calculate due date
  let dueDate: string | null = null;
  if (taskConfig.due_date_offset_days !== undefined) {
    dueDate = addDays(new Date(), taskConfig.due_date_offset_days).toISOString();
  }
  
  // Interpolate text fields
  const title = interpolateTemplate(taskConfig.title, context);
  const description = taskConfig.description
    ? interpolateTemplate(taskConfig.description, context)
    : null;
  
  logger.info('[CreateTask] Creating task:', {
    projectId,
    title,
    status: taskConfig.status || 'todo',
  });
  
  try {
    const { data: task, error } = await supabase
      .from('project_tasks')
      .insert({
        project_id: projectId,
        title,
        description,
        status: taskConfig.status || 'todo',
        priority: taskConfig.priority || 'medium',
        assignee_id: assigneeId,
        due_date: dueDate,
        tags: taskConfig.tags || [],
        ai_generated: true, // Mark as generated by workflow
        dependencies: [],
      })
      .select()
      .single();
    
    if (error) {
      logger.error('[CreateTask] Failed to create task:', {
        error: error.message,
        projectId,
      });
      throw new Error(`Failed to create task: ${error.message}`);
    }
    
    logger.info('[CreateTask] Task created:', {
      taskId: task.id,
      title: task.title,
    });
    
    return {
      output: {
        success: true,
        task_id: task.id,
        task,
        created_at: new Date().toISOString(),
      },
    };
    
  } catch (error) {
    logger.error('[CreateTask] Error:', {
      error: error instanceof Error ? error.message : 'Unknown error',
      projectId,
    });
    throw error;
  }
}

/**
 * Execute update task action
 * 
 * @param config - Task update configuration
 * @param context - Workflow context
 * @returns Action result with updated task details
 */
export async function executeUpdateTask(
  config: UpdateTaskConfig | unknown,
  context: WorkflowContext
): Promise<{ output: unknown }> {
  const taskConfig = config as UpdateTaskConfig;
  const supabase = createAdminSupabaseClient();
  
  // Get task ID from config or context
  let taskId: string | undefined;
  
  if (taskConfig.task_id) {
    taskId = interpolateTemplate(taskConfig.task_id, context);
  } else if (taskConfig.task_field) {
    const fieldValue = getNestedValue(context, taskConfig.task_field);
    taskId = typeof fieldValue === 'string' ? fieldValue : undefined;
  }
  
  if (!taskId) {
    throw new Error('No task ID found for task update');
  }
  
  // Build updates object
  const updates: Record<string, unknown> = {};
  
  if (taskConfig.updates.status !== undefined) {
    updates.status = taskConfig.updates.status;
  }
  
  if (taskConfig.updates.priority !== undefined) {
    updates.priority = taskConfig.updates.priority;
  }
  
  if (taskConfig.updates.assignee_id !== undefined) {
    updates.assignee_id = taskConfig.updates.assignee_id;
  } else if (taskConfig.updates.assignee_field) {
    const fieldValue = getNestedValue(context, taskConfig.updates.assignee_field);
    updates.assignee_id = typeof fieldValue === 'string' ? fieldValue : null;
  }
  
  if (taskConfig.updates.due_date !== undefined) {
    updates.due_date = taskConfig.updates.due_date;
  } else if (taskConfig.updates.due_date_offset_days !== undefined) {
    updates.due_date = addDays(new Date(), taskConfig.updates.due_date_offset_days).toISOString();
  }
  
  // Always update the updated_at timestamp
  updates.updated_at = new Date().toISOString();
  
  if (Object.keys(updates).length === 1) {
    // Only updated_at, nothing meaningful to update
    logger.warn('[UpdateTask] No updates specified');
    return {
      output: {
        success: false,
        skipped: true,
        reason: 'No updates specified',
        task_id: taskId,
      },
    };
  }
  
  logger.info('[UpdateTask] Updating task:', {
    taskId,
    updates: Object.keys(updates).filter(k => k !== 'updated_at'),
  });
  
  try {
    const { data: task, error } = await supabase
      .from('project_tasks')
      .update(updates)
      .eq('id', taskId)
      .select()
      .single();
    
    if (error) {
      logger.error('[UpdateTask] Failed to update task:', {
        error: error.message,
        taskId,
      });
      throw new Error(`Failed to update task: ${error.message}`);
    }
    
    logger.info('[UpdateTask] Task updated:', {
      taskId: task.id,
      updates: Object.keys(updates).filter(k => k !== 'updated_at'),
    });
    
    return {
      output: {
        success: true,
        task_id: task.id,
        updates,
        task,
        updated_at: new Date().toISOString(),
      },
    };
    
  } catch (error) {
    logger.error('[UpdateTask] Error:', {
      error: error instanceof Error ? error.message : 'Unknown error',
      taskId,
    });
    throw error;
  }
}

